### ISSUE TITLE
Realm studio not working in my macBook  

### ISSUE THREAD

**Issue by honeynegi** [realm/realm-object-server#429] opened 2019-10-20 08:42 UTC
## Expected Results

Open Realm studio desktop app.

## Actual Results

“Realm Studio” can’t be opened because Apple cannot check it for malicious software.

## Version of Realm and Tooling

- Realm Object Server Version:3.8.1
- Flavor:
  - [ ] Cloud
  - [ ] Self-hosted
- Server OS & Version: ? (e.g. CentOS 6)
- Client SDK Version: ?
- Client OS & Version: macOS 10.15 (19A602)

## Logs

<details>
  <summary>systemctl status realm-object-server.service</summary>
  <pre>Paste output here</pre>
</details>

<details>
  <summary>sudo journalctl -u realm-object-server.service</summary>
  <pre>Paste output here</pre>
</details>

<details>
  <summary>cat /var/log/realm-object-server.log</summary>
  <pre>“Realm Studio” can’t be opened because Apple cannot check it for malicious software.</pre>
</details>

**Comment by nirinchev** [comment] 2019-10-20 08:52
This is a duplicate of https://github.com/realm/realm-studio/issues/1191. You can check the issue for a workaround.

**Closed by nirinchev** 2019-10-20 08:52 UTC
Labels: O-Community
