### ISSUE TITLE
Can login with Realm Browser but credentials discarded when logging in from iOS

### ISSUE THREAD

**Issue by icanzilb** [realm/realm-object-server#259] opened 2017-08-26 18:05 UTC
## Goals

Login with the same credentials from Realm Browser and an iOS app

## Expected Results

Success.

## Actual Results

Fail.

## Steps to Reproduce

I create a user called 'admin1@host', then use a node app to log in as the user and add some data to a realm file. Then I give read-only permission to that file to another user 'event1@host'.

If I use Realm Browser to open the shared file with 'event1@host' (read-only) I succeed and I can see the data (but cannot modify it as expected).

When I try the same from an iOS app I get the following error message back: 

```
2017-08-26 20:02:02.216 EventBlank2-iOS[19417:2099262] Sync: Connection[1]: Resolving 'localhost:9080'
2017-08-26 20:02:02.222 EventBlank2-iOS[19417:2099262] Sync: Connection[1]: Connecting to endpoint '::1:9080' (1/2)
2017-08-26 20:02:02.222 EventBlank2-iOS[19417:2099262] Sync: Connection[1]: Connected to endpoint '::1:9080' (from '::1:50526')
2017-08-26 20:02:02.227 EventBlank2-iOS[19417:2099262] Sync: Connection[1]: Session[1]: Sending: BIND(server_path='/879774b56c74fe3b9be6e12ea9d9db03/eventblank', signed_user_token_size=645, need_file_ident_pair=1)
2017-08-26 20:02:02.230 EventBlank2-iOS[19417:2099262] Sync: Connection[1]: Session[1]: Received: ALLOC(server_file_ident=1, client_file_ident=5, client_file_ident_secret=4270528502628246291)
2017-08-26 20:02:02.240 EventBlank2-iOS[19417:2099262] Sync: Connection[1]: Session[1]: Sending: IDENT(server_file_ident=1, client_file_ident=5, client_file_ident_secret=4270528502628246291, scan_server_version=0, scan_client_version=0, latest_server_version=0, latest_server_session_ident=0)
2017-08-26 20:02:02.240 EventBlank2-iOS[19417:2099262] Sync: Connection[1]: Session[1]: Sending: MARK(request_ident=1)
2017-08-26 20:02:02.282 EventBlank2-iOS[19417:2099262] Sync: Connection[1]: Session[1]: Received: MARK(request_ident=1)
2017-08-26 20:02:02.285 EventBlank2-iOS[19417:2099262] Sync: Connection[1]: Received: ERROR(error_code=206, message_size=33, try_again=0, session_ident=1)
2017-08-26 20:02:02.285 EventBlank2-iOS[19417:2099262] Sync: Connection[1]: Connection closed due to error reported by server: Permission denied (BIND, REFRESH) (206)
```

I tried adding `readOnly` to the synced realm file configuration (in an effort to find out a workaround) but that also raises an error saying I can't make synced files read-only.

I see few issues here:
* why can I login from the browser and not from iOS?
* why can't I access a file to which I have permission?
* why can't I set a synced file as read-only since I have only read-only permissions to it?

## Version of Realm and Tooling

- Realm Object Server Version: 1.8.3
- Flavor:
  - [ ] Developer
  - [x] Professional
  - [ ] Enterprise
- Server OS & Version: macOS 10.12.6
- Client SDK Version: 2.10
- Client OS & Version: macOS 10.12.6

## Logs

```
2017-08-26T18:02:02.226Z - info: sync: HTTP Connection[118]: Connection from 127.0.0.1:50527
2017-08-26T18:02:02.226Z - info: sync: HTTP Connection[118]: Received: Sync HTTP request(protocol_version=18)
2017-08-26T18:02:02.227Z - info: sync: Sync Connection[118]: Session[1]: Session initiated (session_ident=1).
2017-08-26T18:02:02.228Z - info: sync: Sync Connection[118]: Session[1]: Received: BIND(server_path=/879774b56c74fe3b9be6e12ea9d9db03/eventblank, signed_user_token='...xtjap9KdbJZjhlbyK5cvbJahH+fQ==', need_file_ident_pair=1)
2017-08-26T18:02:02.229Z - info: sync: Sync Connection[118]: Session[1]: Sending: ALLOC(server_file_ident=1, client_file_ident=5, client_file_ident_secret=4270528502628246291)
2017-08-26T18:02:02.240Z - info: sync: Sync Connection[118]: Session[1]: Received: IDENT(server_file_ident=1, client_file_ident=5, client_file_ident_secret=4270528502628246291, scan_server_version=0, scan_client_version=0, latest_server_version=0, latest_server_session_ident=0)
2017-08-26T18:02:02.242Z - info: sync: Sync Connection[118]: Session[1]: Received: MARK(request_ident=1)
2017-08-26T18:02:02.242Z - info: sync: Sync Connection[118]: Session[1]: Sending: MARK(request_ident=1)
2017-08-26T18:02:02.284Z - error: sync: Sync Connection[118]: Session[1]: Permission denied (message_type='upload', path='/879774b56c74fe3b9be6e12ea9d9db03/eventblank').
2017-08-26T18:02:02.284Z - info: sync: Sync Connection[118]: Session[1]: Session terminated (session_ident=1).
2017-08-26T18:02:02.284Z - info: sync: Sync Connection[118]: Sending: ERROR(error_code=206, message_size=33, try_again=0, session_ident=1)
2017-08-26T18:02:02.285Z - info: sync: Sync Connection[118]: Connection closed by client: End of input
```

**Comment by icanzilb** [comment] 2017-08-26 18:10
Further, yes - the user does indeed have that read permission:

![image](https://user-images.githubusercontent.com/633862/29743898-8681fa26-8a9a-11e7-863a-8b5a7bbfdc1c.png)

and the user itself:

![image](https://user-images.githubusercontent.com/633862/29743900-9828dc54-8a9a-11e7-8393-5c3eefa8f5bf.png)

**Comment by bdash** [comment] 2017-08-26 18:12
You haven't shared the code you're using to authenticate + open the Realm in your iOS app. My suspicion is that you're not using async open when opening the Realm, which results in your iOS app creating the schema locally and trying to upload it. This means you end up attempting to perform a write operation on a Realm to which the user has only have read access. Using the async open API means that we don't attempt to open the Realm until it is downloaded, and so we don't modify the schema.

**Comment by icanzilb** [comment] 2017-08-26 18:21
thanks @bdash , here's the complete connect function in the iOS app:

```swift
func connect(user: String, pass: String, completion: @escaping (Bool) -> Void) {
    print("connecting to \(serverUrl)")


    let cred = SyncCredentials.usernamePassword(username: user, password: pass, register: false)

    SyncUser.logIn(with: cred, server: serverUrl) { [weak self] user, error in
        guard let fileUrl = self?.fileUrl else { return }

        if let error = error {
            print("[connect error]: \(error.localizedDescription)")
        }

        guard let user = user else {
            completion(false)
            return
        }

        self?.user = user
        RealmProvider.event.setSyncConfiguration(
            SyncConfiguration(user: user, realmURL: fileUrl))

        Realm.asyncOpen(configuration: RealmProvider.event.configuration, callbackQueue: DispatchQueue.main, callback: { [weak self] realm, error in
            self?.syncedRealm = realm
            completion(error == nil)
        })
    }
}
```

**Comment by bdash** [comment] 2017-08-26 18:50
What does `RealmProvider.event.setSyncConfiguration(…)` do? Does it do anything that could result in the Realm being opened synchronously?

Did you at some point in the past attempt to open the Realm synchronously before switching to async open? If so, you may need to delete and reinstall the app to clear out the changes that sync wants to upload but is unable to due to the permission issue.

**Comment by icanzilb** [comment] 2017-08-26 18:58
`setSyncConfiguration` updates a pre-canned configuration instance like so:

```swift
mutating public func setSyncConfiguration(_ config: SyncConfiguration?) {
    var updated = configuration
    updated.syncConfiguration = config
    configuration = updated
}
```

I deleted the app few times while trying to get connected to make sure there's no login leftovers of any sort. I'll reset the server and let you know if that changes anything.

**Comment by icanzilb** [comment] 2017-08-26 19:05
Ok, I did reset the server, deleted the iOS app from the device, and executed the steps exactly as I described them initially: 
* create the two users via the dashboard
* connect from node.js as the owner and add data
* give read permission to the second user
* connect from realm browser is OK
* connect from the iOS app:

```
2017-08-26 21:06:52.529 EventBlank2-iOS[19898:2146790] Sync: Connection[1]: Received: ERROR(error_code=206, message_size=33, try_again=0, session_ident=1)
2017-08-26 21:06:52.529 EventBlank2-iOS[19898:2146790] Sync: Connection[1]: Connection closed due to error reported by server: Permission denied (BIND, REFRESH) (206)
```

**Comment by icanzilb** [comment] 2017-08-27 09:36
And this is the function which gives the read permissions to the second user:

```
readonly(userId) {
    print('Set '+userId+' as read-only access to the eventblank realm file.');
    const managementRealm = this.user.openManagementRealm();

    managementRealm.write(() => {
        managementRealm.create('PermissionChange', {
        id: uuidV1(),
        createdAt: new Date(),
        updatedAt: new Date(),
        userId: userId,
        realmUrl: this.url,
        mayRead: true,
        mayWrite: false,
        mayManage: false
        });
  });
}
```

**Comment by icanzilb** [comment] 2017-08-27 18:03
@bdash found what the problem is. The iOS schema missed a field that was added in the Node.js app. The Node.js app initially creates the realm file on the server, so when the iOS app connects the schema doesn't match. 

In that context the server error makes more sense `Permission denied (BIND, REFRESH)` but I reckon the real issue here is that the error message is vague. 

In the situation, the error message should be something along the lines of

`Schema mismatch, permission to update schema on the server denied.`

**Comment by morten-krogh** [comment] 2017-09-11 12:39
The 206 permission denied error looks very misplaced. It appears at the "wrong" point in the log
file. 

It is unrelated to the schema mismatch. 

What you see is rather strange.
Did the permission_denied error really disappear because you added a field to the schema?

Can you still reproduce this scenario?

**Comment by icanzilb** [comment] 2017-09-12 07:43
Is this a priority to fix if I can still reproduce it?

**Comment by morten-krogh** [comment] 2017-09-12 08:05
Yes, It looks so strange that I think we need to understand how it could happen.

**Comment by icanzilb** [comment] 2017-09-13 14:37
[259-test.zip](https://github.com/realm/realm-mobile-platform/files/1299772/259-test.zip)

@morten-krogh Do the following:

1. create 2 users on ROS
2. open the Node app in the zip, install modules, and then edit the file to replace the few config constants at the top of the source file - include login for the Read-Write user (the first user you created) and the ID of the read-only (the second user you created)
3. run the node app - it will connect to ROS, create a synced Realm file and give user nr. 2 read-only access
4. open the iOS app, install CocoaPods, edit the config constants in AppDelegate - this time put the login for the read-only and set the ID of the rw user 
5. run the iOS app - it will connect to the shared file, and you will see the error as described in this issue

let me know if you need anything more

**Comment by morten-krogh** [comment] 2017-09-13 14:40
@icanzilb Thank you very much. I will look into it at some point given time.

**Comment by icanzilb** [comment] 2017-09-13 14:45
@morten-krogh For the time being even a correct error message will do wonders for user experience

**Comment by morten-krogh** [comment] 2017-10-27 09:57
@icanzilb 
Sorry for not having had time to look at this.
Do you think it is still relevant for 2.0?

**Comment by icanzilb** [comment] 2017-11-09 18:15
@morten-krogh I can try the same steps as described so far in this thread on ROS 2.0. do you want me to do that?

**Comment by morten-krogh** [comment] 2017-11-09 18:19
@icanzilb Yes, that would be nice if you have time.

**Comment by icanzilb** [comment] 2017-11-10 21:12
@morten-krogh I'm blocked reproducing by https://github.com/realm/realm-studio/issues/394 - at present can't find a user's id. will try again when/if it gets fixed.

**Comment by icanzilb** [comment] 2017-11-27 17:10
It seems the issue is still present. Following the steps I get the following in the console:

```
2017-11-27 18:09:40.517749+0100 259-test[77688:1237901] TIC TCP Conn Failed [3:0x60c000166780]: 1:61 Err(61)
2017-11-27 18:09:40.519359+0100 259-test[77688:1237901] Task <D6752AE8-1AE6-4B46-808B-0775940B5B5A>.<3> HTTP load failed (error code: -1004 [1:61])
2017-11-27 18:09:40.520362+0100 259-test[77688:1237902] Task <D6752AE8-1AE6-4B46-808B-0775940B5B5A>.<3> finished with error - code: -1004
2017-11-27 18:09:40.579761+0100 259-test[77688:1237946] Sync: Connection[1]: Failed to connect to endpoint '::1:9080': Connection refused
2017-11-27 18:09:40.581523+0100 259-test[77688:1237946] Sync: Connection[1]: Connected to endpoint '127.0.0.1:9080' (from '127.0.0.1:64242')
2017-11-27 18:09:40.817425+0100 259-test[77688:1237946] Sync: Connection[1]: Received: ERROR(error_code=206, message_size=33, try_again=0, session_ident=1)
2017-11-27 18:09:40.817725+0100 259-test[77688:1237946] Sync: Connection[1]: Connection closed due to error reported by server: Permission denied (BIND, REFRESH) (206)
```

**Comment by icanzilb** [comment] 2017-11-27 17:11
[node-latest.zip](https://github.com/realm/realm-object-server/files/1506827/node-latest.zip)

@morten-krogh I updated the Node app with the latest syntax

**Comment by icanzilb** [comment] 2017-11-27 17:15
It becomes even more interesting, the permission is on the server:

![image](https://user-images.githubusercontent.com/633862/33279430-cb3d29fe-d39e-11e7-9aa4-bf934e890427.png)

But when I try to connect from Studio with the read-only user I get:

![image](https://user-images.githubusercontent.com/633862/33279461-e67860c6-d39e-11e7-911b-da2a7e4a0d4b.png)

**Comment by morten-krogh** [comment] 2017-11-28 09:20
@icanzilb I will look at it as soon as there is time. Thank you very much for reporting this issue.

**Comment by icanzilb** [comment] 2017-11-28 09:23
@morten-krogh you should discard the last comment about not being able to login with Realm Studio. I've been told users aren't supposed to log in via Realm Studio.

**Comment by morten-krogh** [comment] 2017-11-30 12:12
@icanzilb 

The error is due to the iOS app having a larger schema than the node.js app.

The extra property is

 dynamic var readOnly = true

What happens is that the iOS app async downloads the Realm, and notices that a column is
missing relative to its own definition. Then it adds the column and tries to upload it, and gets the 
permission denied error.

The error goes away either by removing the "readOnly" column in iOS or adding it in js.

**Comment by morten-krogh** [comment] 2017-11-30 12:15
In the future, we might want to catch the error on the client side.
If a client makes changes to a read only Realm, it should be reported immediately on the 
client.

**Comment by icanzilb** [comment] 2017-11-30 14:11
@morten-krogh oh wow! i've lost so much time with this... we should definitely do better on client feedback 😞

**Comment by morten-krogh** [comment] 2017-11-30 14:56
Yes, I think I will close this. Maybe we can open an issue about client behavior when read o nly is violated.

**Closed by morten-krogh** 2017-11-30 14:56 UTC

**Comment by bmunkholm** [comment] 2017-11-30 21:01
@morten-krogh Did you create an issue for it? (if not, please do so we don't loose it)

**Comment by morten-krogh** [comment] 2017-12-01 07:36
@bmunkholm @icanzilb 
Issue opened in object store
https://github.com/realm/realm-object-store/issues/607
