### ISSUE TITLE
HTTP Connection : Connection is closed after HTTP Response

### ISSUE THREAD

**Issue by howdyhyber** [realm/realm-object-server#365] opened 2018-04-30 06:05 UTC
Hi Realm,

I have experienced this issue  whenever i use subscription using graphql. I am using apollo client so that i could do subscription. Sometimes, it works perfectly but after and hour, it cant do subscription anymore because the realm is closed. Though i can still use query and mutation. Please see the logs below.

Loaded feature token
1:54:17 PM
▶context: Object
Realm Object Server version 2.8.1 is starting
1:54:17 PM
Realm sync server started ([realm-core-5.1.2], [realm-sync-2.2.15])
sync1:54:17 PM
Directory holding persistent state: /home/ec2-user/xeleqt-object-server/data/sync/user_data
sync1:54:17 PM
Backup mode: master_with_no_slave
sync1:54:17 PM
Log level: info
sync1:54:17 PM
Download log compaction is enabled
sync1:54:17 PM
Max download size: 32000000 bytes
sync1:54:17 PM
Listening on 127.0.0.1:34505 (sync protocol version 22)
sync1:54:17 PM
HTTP Connection[1]: Connection is closed after HTTP response.
sync1:54:17 PM
HTTP Connection[3]: Connection is closed after HTTP response.
sync1:54:17 PM
HTTP Connection[4]: Connection is closed after HTTP response.
sync1:54:17 PM
HTTP Connection[7]: Connection is closed after HTTP response.
sync1:54:18 PM
HTTP Connection[9]: Connection is closed after HTTP response.
sync1:54:18 PM
HTTP Connection[11]: Connection is closed after HTTP response.
sync1:54:18 PM
HTTP Connection[12]: Connection is closed after HTTP response.
sync1:54:18 PM
HTTP Connection[15]: Connection is closed after HTTP response.
sync1:54:18 PM
HTTP Connection[17]: Connection is closed after HTTP response.
sync1:54:18 PM
HTTP Connection[19]: Connection is closed after HTTP response.
sync1:54:18 PM
HTTP Connection[20]: Connection is closed after HTTP response.
sync1:54:18 PM
HTTP Connection[24]: Connection is closed after HTTP response.
sync1:54:18 PM
Realm Object Server has started and is listening on http://0.0.0.0:9080
1:54:18 PM
HTTP Connection[30]: Connection is closed after HTTP response.

Hope someone can help ASAP. Thanks :smile: 
God Bless!

**Comment by astigsen** [comment] 2018-07-31 11:16
Closing this for now since it refers to an old version of ROS, and so the issue is likely fixed by now. Please reopen if it resurfaces.

**Closed by astigsen** 2018-07-31 11:16 UTC
