### ISSUE TITLE
Sync Only Local

### ISSUE THREAD

**Issue by luigidegiacomo** [realm/realm-object-server#363] opened 2018-04-26 00:59 UTC
## Goals

I want sync Local & Remote Realm with Realm Cloud

## Expected Results
On Realm Cloud (inspected with Realm Studio) only Realm is created, but nothing classes in.

## Actual Results

MyApp run great on iPhone but don't sync with Realm Cloud

Please help me

**Comment by astigsen** [comment] 2018-07-31 09:47
Closing this for now as no code to reproduce the problem was supplied. Please reopen with more info if the problem persists.

**Closed by astigsen** 2018-07-31 09:47 UTC
